# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 00:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_change_studnet_class_to_many'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='classroom',
            new_name='classrooms',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='classroom',
            new_name='classrooms',
        ),
    ]
