# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_classrooms_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
